This is makeindex, version 2.15 [TeX Live 2021] (kpathsea + Thai support).
Scanning style file ./NIR.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file NIR.acn....done (50 entries accepted, 0 rejected).
Sorting entries....done (283 comparisons).
Generating output file NIR.acr....done (110 lines written, 0 warnings).
Output written in NIR.acr.
Transcript written in NIR.alg.
